### ISSUE TITLE
Problem with dimmer 2

### ISSUE THREAD

**Issue by OZEO-DOOZ** [jbasen/Crestron-Shelly#11]
Hi,

I got instability with the control of the dimmer 2.
Do you know what is the problem? Sometime it works and sometime it does not work.

Shelly - Send_Dimmer_Command - URL: http://192.168.1.199/light/0?turn=on&brightness=53
Shelly - Send_Dimmer_Command - Error Sending Device Command: Crestron.SimplSharp.Net.Http.HttpException: Not Found
   at Crestron.SimplSharp.Net.Http.HttpClient.Dispatch(HttpClientRequest aRequest)
   at Shelly_Integration.Shelly.Send_Dimmer_Command(String Device_IP, Int16 Command, UInt16 Brightness, String Username, String Password)
   at UserModule_SHELLY_DIMMER_V2.UserModuleClass_SHELLY_DIMMER_V2.BRIGHTNESS_OnChange_5(Object __EventInfo__)
   at Amib.Threading.Internal.WorkItem.o()
   at Amib.Threading.Internal.WorkItem.Execute()
   at Amib.Threading.SmartThreadPool.e(WorkItem A_0)
   at Amib.Threading.SmartThreadPool.p()

---

Shelly_Dimmer_Brightness
Shelly - Send_Dimmer_Command - Device_IP = 192.168.1.199, Username = , Password = , Command = 4, Level = 60
Shelly - Send_Dimmer_Command - URL: http://192.168.1.199/light/0?turn=on&brightness=60
Shelly - Send_Dimmer_Command - Error Sending Device Command: Crestron.SimplSharp.Net.Http.HttpException: Not Found
   at Crestron.SimplSharp.Net.Http.HttpClient.Dispatch(HttpClientRequest aRequest)
   at Shelly_Integration.Shelly.Send_Dimmer_Command(String Device_IP, Int16 Command, UInt16 Brightness, String Username, String Password)
   at UserModule_SHELLY_DIMMER_V2.UserModuleClass_SHELLY_DIMMER_V2.BRIGHTNESS_OnChange_5(Object __EventInfo__)
   at Amib.Threading.Internal.WorkItem.o()
   at Amib.Threading.Internal.WorkItem.Execute()
   at Amib.Threading.SmartThreadPool.e(WorkItem A_0)
   at Amib.Threading.SmartThreadPool.p()

**Comment by OZEO-DOOZ** [comment]
No idea?

**Comment by jbasen** [comment]
Sorry, I wrote a long post days ago and somehow it never posted.  Sigh.  Let me try and reconstruct my thoughts again.

From what you posted I'm assuming that you are seeing the same command, with the exception of the brightness level, intermittently work vs. throw the errors you show above.  Please correct me if I'm wrong.

In this case the problem appears to be outside of the shelly-crestron modules as they are sending an identical http command and sometimes the command is reaching the shelly dimmer and sometimes it isn't.  I can think of two potential reasons for this.  

1) There is a network problem that is interfering with communications.  Sometimes the http command makes it through and sometimes it doesn't.

2) The Shelly device has a problem and sometimes it is in a state where it accepts the http command and sometimes it is in an error condition and won't accept an http command.

The basic command being sent by the Shelly-Crestron module is:

http://192.168.1.199/light/0?turn=on&brightness=<brightness level between 0 and 100>

You can see this in the url that you posted.    If you have multiple Shelly dimmers and this is happening with all of them then I would suspect a network problem.  If you have multiple shelly dimmers and this only happens with one I would suspect the dimmer that is intermittent.  

On thing you can try is to simply type the url into the address bar of your browser and send it from there.  I expect you'll see similar results as from the Crestron program through the header information sent by a browser will be different and could cause slightly different results.  

You might also try contacting Shelly support about the problem as there are other people using the modules without seeing the problem that you are.

Hope this help
